### ISSUE TITLE
Timeline height increasing on window resize event

### ISSUE THREAD

**Issue by bodnarbm** [Asymmetrik/angular2-sentio#15]
When using the `sentioTimeline` directive, I see the height of the timeline increasing on every window resize event. This does not happen if the height for the element is set to a specific height using a style attribute.

I will see if I can create a simple example showcasing the problem.

> Version Info:
> @asymmetrik/angular2-sentio = 3.1.1
> @asymmetrik/sentio = 3.0.2
> d3 = 4.5.0

**Comment by reblace** [comment]
Should be resolved by #17

**Comment by reblace** [comment]
Fixed in 3.1.2
